### ISSUE TITLE
isCommonInterval(x) must ignore declaration part

### ISSUE THREAD

**Issue by nadezhin** [nehmeier/libieeep1788#10]
Section 11.7.2 says that the boolean operation acts on decorated intervals by discarding the decoration and applying the corresponding bare interval
operation. 
So I expect that
 is_common([-5.7,8.3]_dac) = true.
Library returns
 is_common([-5.7,8.3]_dac) = false.

**Comment by nehmeier** [comment]
That is true.

But it is probably a misleading definition or naming of the function if
is_common returns true for an interval with a decoration != com

**Comment by nadezhin** [comment]
The name of the function in the draft is "isCommonInterval(x)".
It might be intuitive if read it as "interval part is a common interval".

Will be this reference implementation more clear, if you names of back-end functions match the
names in the draft ? For example,
representation interval_part(representation_dec const& x);
instead of
representation constructor(representation_dec const& x);

**Comment by nehmeier** [comment]
Good point.

I think I will refactor my backend


----------------------------------------------------------------------
Dipl.-Inform. Marco Nehmeier

Chair of Software Engineering
Department of Computer Science
University of Würzburg

Am Hubland, Informatikgebäude, Room A111
97074 Würzburg, Germany

Phone: +49 931 31 88684, Fax +49 931 31 86603
mailto:nehmeier@informatik.uni-wuerzburg.de
http://go.uni-wuerzburg.de/nehmeier
---------------------------------------------------------------------

Am 06.02.2015 um 13:24 schrieb nadezhin:
