### ISSUE TITLE
is_empty and is_entire on NaI must be undefined

### ISSUE THREAD

**Issue by oheim** [nehmeier/libieeep1788#12]
see 11.7.2.

The minimal_is_empty_dec_test and minimal_is_entire_dec_test should fail if decoration is ill.

**Comment by nadezhin** [comment]
Section 11.7.2 says that operation has no value at level 1.
Section 12.12.9 specifies behaviour at level 2. It says that the result of these operations is false if any input is NaI. Library returns false correctly.

**Comment by oheim** [comment]
Thanks for the explanation
