### ISSUE TITLE
pownRev(x,-2) is not the tightest

### ISSUE THREAD

**Issue by nadezhin** [nehmeier/libieeep1788#18]
I expect that
 pownRev([0x1.0000000000002p-2,+inf],-2) = [1,0x1.fffffffffffffp0]
because pown([0x1.fffffffffffffp0],-2) < 0x1.0000000000002p-2
but the library returns
 pownRev([0x1.0000000000002p-2,+inf],-2) = [1,2]

**Comment by nehmeier** [comment]
The standard requires only an __accurate__ accuracy for pownRev.
Hence the result of pownRev is ok...

But I will try to improve the accuracy of pownRev in a future release.
